name: APK Builder
on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'Target github repo'     
        required: true
        default: 'shiveshnavin/instagram-automation-app'
      gradle_wrapper_version:
        description: 'Gradle Wrapper version'     
        required: true
        default: '7.0.2'
env:
  gradle_wrapper_version: ${{ github.event.inputs.gradle_wrapper_version }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.target_repo }}
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: List checked out files
        run: ls
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Get gradle wrapper
        run: gradle wrapper --gradle-version $gradle_wrapper_version
      - name: Build Android App
        run: sh gradlew build
      - name: Save APK
        uses: actions/upload-artifact@v3
        with:
          name: output.apk
          path: |
            app/build/outputs/apk/debug/app-debug.apk
